// Generated by https://quicktype.io

export interface Auth {
    ok:    boolean;
    msg:   string;
    user:  User;
    token: string;
}

export interface User {
    _id:       string;
    name:      string;
    email:     string;
    createdAt: string;
    updatedAt: string;
}
