// Generated by https://quicktype.io

export interface FetchAllkeysResponse {
    keys: Key[];
}

export interface Key {
    _id:         string;
    name:        string;
    description: string;
    receivedBy:  string;
    createdAt:   string;
    updatedAt:   string;
    image?:      string;
}


