export interface AuthState {
  status: "checking" | "authenticated" | "not-authenticated";
  uid: string;
  roles: string[];
  name: string;
  email: string;
}

// Generated by https://quicktype.io
export interface IUser {
  fullName: string;
  email: string;
  updated_at: Date | null;
  deleted_at: Date | null;
  id: string;
  roles: string[];
  created_at: Date;
}

export interface IFetchAuth {
  user: IUser;
  token: string;
}

export interface ILoginUser {
  email: string;
  password: string;
}
