export interface AuthState {
    status: 'checking' | 'authenticated' | 'not-authenticated';
    uid: string | null;
    role: string;
    name: string | null;
    email: string | null;
    errorMsj: string | null;
}

// Generated by https://quicktype.io

export interface FetchAuth {
    ok:    boolean;
    msg:   string;
    user:  User;
    token: string;
}

export interface User {
    _id:       string;
    name:      string;
    email:     string;
    role:      string;
    status:    boolean;
    createdAt: string;
    updatedAt: string;
}

