// Generated by https://quicktype.io

export interface Key {
    ok:           boolean;
    msg:          string;
    responseItem: ResponseItem;
}

export interface ResponseItem {
    name:        string;
    description: string;
    receivedBy:  string;
    _id:         string;
    createdAt:   string;
    updatedAt:   string;
}

export interface Keys{
    name:        string;
    description: string;
    receivedBy:  string;
    _id:         string;
    createdAt:   string;
    updatedAt:   string;
}
